on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: acrdemo2021amir.azurecr.io
        username: ${{ secrets.acr_acrdemo2021amir_username }}
        password: ${{ secrets.acr_acrdemo2021amir_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t acrdemo2021amir.azurecr.io/aksdemoamir:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push acrdemo2021amir.azurecr.io/aksdemoamir:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_aksdemoamir_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep aks-demo-amirafc2 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace aks-demo-amirafc2`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: aks-demo-amirafc2
        container-registry-url: acrdemo2021amir.azurecr.io
        container-registry-username: ${{ secrets.acr_acrdemo2021amir_username }}
        container-registry-password: ${{ secrets.acr_acrdemo2021amir_password }}
        secret-name: aksdemoamirdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: aks-demo-amirafc2
        manifests: |
          manifests/deployment-3.yml
          manifests/service-3.yml
        images: |
          acrdemo2021amir.azurecr.io/aksdemoamir:${{ github.sha }}
        imagepullsecrets: |
          aksdemoamirdockerauth
